### ISSUE TITLE
Duplicated events

### ISSUE THREAD

**Issue by alexandreliberato** [nithincvpoyyil/mixpanel-tools#1] opened 2019-06-21 14:12 UTC
It's duplicating events on events view, even the time is the same.
Though on mixpanel Live view does not show duplicated .

![image](https://user-images.githubusercontent.com/300424/59928601-79312a00-9415-11e9-9dd5-bd310dd9d177.png)

**Comment by nithincvpoyyil** [comment] 2019-07-27 02:54
@psybox : thanks for raising the issue, Let me check..

**Comment by nithincvpoyyil** [comment] 2019-10-26 01:12
@psybox :  I have tried multiple apps to recreate this issue, however, I couldn't recreate this issue and events are showing without duplicates. I'm closing this ticket as of now,  If there is any specific case if you found, please let me know and raise an issue. Thank you for the feedback. _nithin

**Closed as completed by nithincvpoyyil** 2019-10-26 01:12 UTC
Labels: bug, duplicate events

**Comment by daroczig** [comment] 2023-01-30 14:35
I am experiencing this issue as well. In the Network tab of devtools, I see 2-2 requests (one is for the service worker, the other is the normal network request) going to the Mixpanel API, and two events showing up in the Mixpanel Tools tab.

Please let me know what to check for you to help debug this.

Thanks,
Gergely

**Comment by daroczig** [comment] 2023-03-03 19:55
To follow-up on the above and share more details: I think the cause of the duplicated events is the use of service works (for PWA), and probably that's why it was not easy to replicate, as you need to register that for a reproducible example. Sharing a pointer here if it might be useful https://web.dev/learn/pwa/service-workers/
