### ISSUE TITLE
No event or property is shown to the user

### ISSUE THREAD

**Issue by mmattana** [nithincvpoyyil/mixpanel-tools#6] opened 2019-12-17 14:18 UTC
I would love to use mixpanel-tools but as for today, dec-17-2019, it isn't working. I've tested in three different computers in windows and ubuntu os'. No event or property is shown on the screen.

**Comment by nithincvpoyyil** [comment] 2019-12-19 04:31
@mmattana : itsmostly due to this issue, https://github.com/nithincvpoyyil/mixpanel-tools/issues/7#issue-539364003

[**Edit**]: Issue reported is not due to above changes, If possible, could you please share the website / web app URL you are used to test? It is working with every application that I have tested(including mixpanel.com).

**Comment by nithincvpoyyil** [comment] 2020-01-24 14:17
@mmattana : Thank you for your contribution, I have changed the API endpoints in the new release, and tested. I couldn't able to reproduce this issue. Currently, I don't have a Ubuntu machine with me, so if it is happening in Ubuntu-chrome, please raise it as a separate issue. I'm closing this ticket as of now.

**Closed as completed by nithincvpoyyil** 2020-01-24 14:17 UTC
Labels: investigating
